// Mock team/directors data for Nalanda Learning
export const teamMembers = [
  {
    id: 1,
    name: 'Dr. Rajesh Kumar Sharma',
    designation: 'Chairman & Managing Director',
    image: '/images/team/director-1.jpg',
    bio: 'Visionary leader with 20+ years in education technology and policy development. Led NEP 2020 implementation frameworks and established key government partnerships.',
    linkedin: 'https://linkedin.com/in/rajesh-sharma',
    twitter: 'https://twitter.com/rajesh_sharma',
    email: 'rajesh.sharma@nalandalearning.in',
  },
  {
    id: 2,
    name: 'Ms. Priya Mehta',
    designation: 'Executive Director & COO',
    image: '/images/team/director-2.jpg',
    bio: 'Operations expert with MBA from IIM Bangalore. Scaled operations to serve 2M+ students and led development of award-winning SaaS platform.',
    linkedin: 'https://linkedin.com/in/priya-mehta',
    twitter: 'https://twitter.com/priya_mehta',
    email: 'priya.mehta@nalandalearning.in',
  },
  {
    id: 3,
    name: 'Dr. Amit Patel',
    designation: 'Director of Technology & Innovation',
    image: '/images/team/director-3.jpg',
    bio: 'Technology visionary with Ph.D. from IISc Bangalore. Leads AI initiatives and developed learning analytics platform serving millions of learners.',
    linkedin: 'https://linkedin.com/in/amit-patel',
    twitter: 'https://twitter.com/amit_patel_ai',
    email: 'amit.patel@nalandalearning.in',
  },
  {
    id: 4,
    name: 'Dr. Sunita Agarwal',
    designation: 'Director of Academic Affairs',
    image: '/images/team/director-4.jpg',
    bio: 'Acclaimed educator with 18+ years in early childhood education. Designed curriculum for 1000+ ECCE programs and trained 5000+ teachers.',
    linkedin: 'https://linkedin.com/in/sunita-agarwal',
    email: 'sunita.agarwal@nalandalearning.in',
  },
  {
    id: 5,
    name: 'Mr. Vikram Singh',
    designation: 'Director of Strategic Partnerships',
    image: '/images/team/director-5.jpg',
    bio: 'Partnership expert with MBA from XLRI. Established collaborations with 15+ government bodies and negotiated MoUs worth ₹500+ crores.',
    linkedin: 'https://linkedin.com/in/vikram-singh',
    twitter: 'https://twitter.com/vikram_partnerships',
    email: 'vikram.singh@nalandalearning.in',
  },
  {
    id: 6,
    name: 'Dr. Meera Krishnan',
    designation: 'Head of Research & Analytics',
    image: '/images/team/director-6.jpg',
    bio: 'Data scientist with expertise in educational research. Leads learning analytics initiatives and published 20+ research papers on EdTech.',
    linkedin: 'https://linkedin.com/in/meera-krishnan',
    email: 'meera.krishnan@nalandalearning.in',
  },
  {
    id: 7,
    name: 'Ms. Kavita Sharma',
    designation: 'Rural Education Specialist',
    image: '/images/team/director-7.jpg',
    bio: 'Rural development expert focused on sustainable education models. Implemented programs in 200+ villages across 10 states.',
    linkedin: 'https://linkedin.com/in/kavita-sharma',
    email: 'kavita.sharma@nalandalearning.in',
  },
  {
    id: 8,
    name: 'Dr. Anita Desai',
    designation: 'Child Development Specialist',
    image: '/images/team/director-8.jpg',
    bio: "Child psychologist with expertise in early learning. Consultant to UNICEF and author of 'Foundations of Early Learning' bestseller.",
    linkedin: 'https://linkedin.com/in/anita-desai',
    email: 'anita.desai@nalandalearning.in',
  },
  {
    id: 9,
    name: 'Mr. Rohit Gupta',
    designation: 'Head of Product Development',
    image: '/images/team/director-9.jpg',
    bio: 'Product management expert with 12+ years in EdTech. Led development of mobile learning apps used by 1M+ students.',
    linkedin: 'https://linkedin.com/in/rohit-gupta',
    twitter: 'https://twitter.com/rohit_product',
    email: 'rohit.gupta@nalandalearning.in',
  },
  {
    id: 10,
    name: 'Ms. Deepika Rao',
    designation: 'Head of Marketing & Communications',
    image: '/images/team/director-10.jpg',
    bio: 'Marketing strategist with expertise in education sector. Built brand presence across digital channels and led successful campaigns.',
    linkedin: 'https://linkedin.com/in/deepika-rao',
    twitter: 'https://twitter.com/deepika_marketing',
    email: 'deepika.rao@nalandalearning.in',
  },
  {
    id: 11,
    name: 'Dr. Arjun Nair',
    designation: 'Head of Quality Assurance',
    image: '/images/team/director-11.jpg',
    bio: 'Quality expert ensuring MEPSC compliance and educational standards. Developed quality frameworks adopted by 500+ institutions.',
    linkedin: 'https://linkedin.com/in/arjun-nair',
    email: 'arjun.nair@nalandalearning.in',
  },
  {
    id: 12,
    name: 'Ms. Ritu Pandey',
    designation: 'Head of Human Resources',
    image: '/images/team/director-12.jpg',
    bio: 'HR leader focused on talent development and organizational culture. Built diverse teams and implemented innovative learning programs.',
    linkedin: 'https://linkedin.com/in/ritu-pandey',
    email: 'ritu.pandey@nalandalearning.in',
  },
];
